apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ezio-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ezio
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Pods
    pods:
      metric:
        name: buy_total
      target:
        type: AverageValue
        averageValue: 10