apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: default
data:
  config.yaml: |
    rules:

    - seriesQuery: 'starlette_request_duration_seconds_count'
      resources:
        overrides:
          kubernetes_namespace:
            resource: namespace
          kubernetes_pod_name:
            resource: pod
      name:
        metricsQuery: starlette_request_duration_seconds_count{app_name="starlette", status_code="200"}
